# This file was generated by GoReleaser. DO NOT EDIT.
class Terratag < Formula
  desc "Automatically create and maintain tags across their entire set of AWS, Azure, and GCP resources on Terraform"
  homepage "https://github.com/env0/terratag"
  version "0.1.26"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/env0/terratag/releases/download/v0.1.26/terratag_0.1.26_darwin_amd64.tar.gz"
    sha256 "5c722f4fde474ca368b2984193879dcc18f5c3aaa0be4f305fe18b04f4a63558"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/env0/terratag/releases/download/v0.1.26/terratag_0.1.26_linux_amd64.tar.gz"
      sha256 "f06c450433dd7ee04053ff9bb300fddfb4e52a36b86209ca3402dad32e86fc90"
    end
  end

  def install
    bin.install "terratag"
  end
end
